apiVersion: v1
entries:
  application-chart:
  - apiVersion: v1
    appVersion: 2.1.0
    created: "2020-11-02T21:29:31.553252291Z"
    description: Helm chart for Open Cluster Management application UI
    digest: 5c1006cef05cdefdb4b97dc543a8d64db82fdd103919bed1811bac1bbd130a72
    keywords:
    - ui
    name: application-chart
    urls:
    - http://multiclusterhub-repo:3000/charts/application-chart-2.2.0.tgz
    version: 2.2.0
  cert-manager:
  - apiVersion: v1
    appVersion: 0.10.3
    created: "2020-11-02T21:29:31.556766234Z"
    dependencies:
    - alias: crd
      condition: cert-manager-crd.enabled
      name: cert-manager-crd
      repository: file://cert-manager-crd
      version: 3.4.0
    description: Service for issuing and managing certificates.
    digest: 37f2fc2bcaefa13b6b02a6e178eadb9d6c1da471158ed77ddd450366e7a5947e
    keywords:
    - amd64
    - ppc64le
    - s390x
    - OpenSource
    - Security
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - RHOCP
    - ROKS
    name: cert-manager
    urls:
    - http://multiclusterhub-repo:3000/charts/cert-manager-2.2.0.tgz
    version: 2.2.0
  cert-manager-webhook:
  - apiVersion: v1
    appVersion: 0.10.3
    created: "2020-11-02T21:29:31.559463229Z"
    description: A Helm chart for deploying the cert-manager webhook component
    digest: 487bf8fce349c35d4fb2f1d9dd51a84171ddafe3b52b3c946e092b3cc4140d03
    home: https://github.com/jetstack/cert-manager
    keywords:
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - amd64
    - ppc64le
    - s390x
    - Commercial
    - RHOCP
    name: cert-manager-webhook
    sources:
    - https://github.com/jetstack/cert-manager
    urls:
    - http://multiclusterhub-repo:3000/charts/cert-manager-webhook-2.2.0.tgz
    version: 2.2.0
  configmap-watcher:
  - apiVersion: v1
    appVersion: 3.7.0
    created: "2020-11-02T21:29:31.56105161Z"
    description: A helm chart for deploying the config map watcher component.
    digest: b16298142031607e451b66214ca02acfc3c7e422a3a4e341f8479ef166c60cd3
    keywords:
    - configmap
    - watcher
    - kubernetes
    - ICP
    - amd64
    - s390x
    - ppc64le
    - Tools
    - Development
    - Tech
    name: configmap-watcher
    urls:
    - http://multiclusterhub-repo:3000/charts/configmap-watcher-2.2.0.tgz
    version: 2.2.0
  console-chart:
  - apiVersion: v1
    appVersion: 2.0.0
    created: "2020-11-02T21:29:31.562889855Z"
    dependencies:
    - alias: crd
      name: console-crd
      repository: file://console-crd
      version: 2.0.0
    description: Helm chart for Open Cluster Management console UI
    digest: 5bfc9feeeca5a8e54d35aaa5d6d11c6415cbff86729568fc2810a5690b0303c4
    keywords:
    - ui
    kubeVersion: '>=1.10.0-0'
    name: console-chart
    urls:
    - http://multiclusterhub-repo:3000/charts/console-chart-2.2.0.tgz
    version: 2.2.0
  grc:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2020-11-02T21:29:31.56341964Z"
    description: helm chart for multicloud grc
    digest: 82f35f9162cc9253d76447fbe72f5ecdd38615104881b494b9120406044f56a2
    keywords:
    - acm
    - grc
    name: grc
    urls:
    - http://multiclusterhub-repo:3000/charts/grc-2.2.0.tgz
    version: 2.2.0
  kui-web-terminal:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2020-11-02T21:29:31.564268713Z"
    description: A helm chart for deploying the Red Hat Visual Web Terminal
    digest: 05e965264097b726ceb55566f3f6ed91519a0764cdadbb9d5b9afb3f3608e455
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0-0'
    name: kui-web-terminal
    urls:
    - http://multiclusterhub-repo:3000/charts/kui-web-terminal-2.2.0.tgz
    version: 2.2.0
  management-ingress:
  - apiVersion: v1
    appVersion: 3.4.0
    created: "2020-11-02T21:29:31.565271229Z"
    description: Multi Cloud control plane ingress controller
    digest: 25345dc7ed71cf057db945666338dc03606e540a0113fbf94aad1e4f4e49ab1d
    keywords:
    - ingress
    - nginx
    - Network
    - Commercial
    - Limited
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0-0'
    name: management-ingress
    urls:
    - http://multiclusterhub-repo:3000/charts/management-ingress-2.2.0.tgz
    version: 2.2.0
  rcm:
  - apiVersion: v1
    appVersion: "2.1"
    created: "2020-11-02T21:29:31.56613023Z"
    description: A helm chart for deploying the cluster lifecycle
    digest: 276ca375b9c44a31e7c631479586d9538ad515369045673b1bdcf8f51c4963eb
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0-0'
    name: rcm
    urls:
    - http://multiclusterhub-repo:3000/charts/rcm-2.2.0.tgz
    version: 2.2.0
  search-prod:
  - apiVersion: v1
    appVersion: 2.2.0
    created: "2020-11-02T21:29:31.567156895Z"
    description: Helm chart to install the Open Cluster Management Search service
    digest: 852841898f605998cff4676ab04f4bdbba7397e908767c78dde11a713c894b0b
    icon: https://raw.githubusercontent.com/kubernetes/kubernetes/master/logo/logo.png
    keywords:
    - RHACM
    - RHOCP
    - ICPRHOCP
    - multicloud
    - multicluster
    - search
    - amd64
    - runtime
    name: search-prod
    urls:
    - http://multiclusterhub-repo:3000/charts/search-prod-2.2.0.tgz
    version: 2.2.0
  topology:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2020-11-02T21:29:31.567626053Z"
    description: helm chart for multicloud topology
    digest: b5352101675e173cbdc55e603e4c825785b8de0c9ec19931b9eada1f76b07e18
    keywords:
    - acm
    - topology
    name: topology
    urls:
    - http://multiclusterhub-repo:3000/charts/topology-2.2.0.tgz
    version: 2.2.0
generated: "2020-11-02T21:29:31.552539254Z"
